### PR TITLE
Added in check for Libselinux-python prior to repo copy

### PR DESCRIPTION
**Pull request by knechtionscoding**
After trying to run the playbook against a minimal CentOS installation it failed looking for the libselinux package. Added in a task to install libselinux-python in elasticsearch/main.yml and then register itself. Added conditional check to the copy elasticsearch repo. Verified that the ansible playbook still ran and test came back clean. ELK gets installed properly now on a CentOS-7-1511 Minimal Install without further modification.

### CODE REVIEW

**Comment by knechtionscoding** [comment]
Related to issue Need check for libselinux-python #31

**Comment by sadsfae** [comment]
Thanks for submitting this, I should get some time in the next week or two to get this reviewed and merged.

**Comment by knechtionscoding** [comment]
I apologize for the extra commits. Only the first few were supposed to be submitted. Once I realized it was still adding them to the PR I changed the files back to the defaults and cloned the whole thing into my own repo.

**Comment by sadsfae** [comment]
I might be missing something here but we already install ```libsemanage-python``` here:

https://github.com/sadsfae/ansible-elk/blob/278fda15e95639d1dbb5cff1ec739a49b0ac515a/install/roles/nginx/tasks/main.yml#L17

This pulls in the all the correct dependencies on CentOS7

```
Installing:
 libsemanage-python         x86_64    2.5-5.1.el7_3            updates    104 k
Updating:
 selinux-policy-targeted    noarch    3.13.1-102.el7_3.16      updates    6.4 M
 systemd                    x86_64    219-30.el7_3.9           updates    5.2 M
Updating for dependencies:
 libgudev1                  x86_64    219-30.el7_3.9           updates     77 k
 libselinux                 x86_64    2.5-6.el7                base       161 k
 libselinux-python          x86_64    2.5-6.el7                base       234 k
 libselinux-utils           x86_64    2.5-6.el7                base       151 k
 libsemanage                x86_64    2.5-5.1.el7_3            updates    144 k
 libsepol                   x86_64    2.5-6.el7                base       288 k
 policycoreutils            x86_64    2.5-11.el7_3             updates    841 k
 selinux-policy             noarch    3.13.1-102.el7_3.16      updates    414 k
 systemd-libs               x86_64    219-30.el7_3.9           updates    369 k
 systemd-sysv               x86_64    219-30.el7_3.9           updates     64 k
```

Have you seen issues where it was needed earlier?  We do most of the heavy lifting in the later playbooks, even parts from other pieces of the stack due to the dependency order that ELK/EFK needs.

**Comment by knechtionscoding** [comment]
When I ran the playbook against an unmodified CentOS minimal installation it failed because it needed the libselinux-python library installed prior to the elasticsearch role running. If it is installed in the nginx role then we might consider moving it to the elasticsearch role.

**Comment by sadsfae** [comment]
@KnechtionsCoding got it, I think I'd just rather install this prior to where you encountered an error.  Thank you for the PR on this, please see if this fixes it for you:

https://github.com/sadsfae/ansible-elk/commit/7d82432472256e6a1f3669fee7797a3c6e0a709a

**Comment by knechtionscoding** [comment]
Absolutely. I'll test it and get back to you later this week.

**Comment by knechtionscoding** [comment]
@sadsfae I've confirmed that this now works on a minimal install of Centos 7. Prior to running only yum update was run. Just so you are aware, I had the same issue in the elk-client role (prior to the installation of filebeat). I can submit a PR for that as well, or you can move the libselinuxmanage to prior to the installation or as a requirement for filebeat.

This is PR can now be closed.

**Pull request closed without merging**
